# order of inclusion from left to right, may override or raise error depending on the options
# NOTE: relative path will be relative to the main config file
include_files=["file1.toml", "dir1/file2.toml"]

# basic options
[basic]
mock_env_fedora_version = "29"
mock_env_fedora_arch= "x86_64"
image_fedora_version = "29"
image_fedora_arch = "x86_64"
base_kickstart_tag="latest" # can also be value like "0.29.2"
os_name="fedora-kd" 
first_login_script="first_login.sh" # put in profile.d to launch at first login
post_build_script="post_script.sh" # post build script
post_build_script_no_chroot="post_no_chroot_script.sh" # post build script in no chroot
user_files=["path_to_dir1", "path_to_dir2"] # will be put in /usr/share/hatter_user_file

# define list of repos
# $releasever and $basearch will be replaced when doing build
[repo]
additional_repos="google-chrome, nvidia" # commonly used repos

    # start defining custom repos here
    [[repo.repo_list]]
    name="rpmfusion-free-updates"
    display_name="RPM Fusion for Fedora $releasever - Free - Updates" 
    enabled=true
    metalink="https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch"
    baseurl="http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/"
    gpgcheck=true
    gpgkey="file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever"
    install=true

    [[repo.repo_list]]
    name="rpmfusion-free"
    display_name="RPM Fusion for Fedora $releasever - Free" 
    enabled=true
    metalink="https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch"
    baseurl="http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/"
    gpgcheck=true
    gpgkey="file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever"
    install=true

# define multiple types of packages to be included
[package]
    [package.rpm.include]
    packages=[
    "moreutils",
    "jq",
    "ripgrep",
    "gnome-terminal"
    ]

    groups=[
    "@multimedia",
    "@sound-and-video"
    ]

    [package.rpm.exclude]
    packages=[
        "gnome-calculator"
    ]

    groups=[
        "@virtualization"
    ]

    [package.snap]
    include = [
        "telegram-desktop"
    ]

    # packages that is installed with --classic flag
    include_classic = [
        "code"
    ]

    exclude=[
        "notepad-plus-plus"
    ]

    [package.flatpak]
    include = [
        "com.spotify.Client",
        "org.octave.Octave"
    ]

    exclude = [
        "org.libreoffice.LibreOffice",
        "org.gimp.GIMP"
    ]

[misc]
lang="en_US.UTF-8" # locale -a
keyboard="us" # localectl list-x11-keymap-layouts
timezone="US/Pacific" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones