# order of inclusion from left to right, may override or raise error depending on the options
# top level and then left to right high to low priority
# NOTE: relative path will be relative to the main config file
include_files=["child_setting_1.toml", "child_path/child_setting_2.toml"]
# include_files=["child_setting_1.toml"]

[distro_info]
base_kickstart_tag="latest" 
base_spin="cinnamon"
os_name="fedora-kd" 

[image_info]
partition_size=7000
first_login_script="first_login.sh" # put in profile.d to launch at first login
post_build_script="post_script.sh" # post build script
post_build_script_no_chroot="post_no_chroot_script.sh" # post build script in no chroot
user_files=["path_to_dir1", "path_to_dir2"] # will be put in /usr/share/hatter_user_file

[build_process]
custom_mock_script="script.sh" # custom script to run in mock env
enable_custom_cache=true

# define list of repos
# $releasever and $basearch will be replaced when doing build
[repo]
standard_repos=["google-chrome", "nvidia", "vscode"]
copr_repos=["khoitd1997/toml11"]
sklfjlsd="flasd"

    # start defining custom repos here
    [[repo.custom_repos]]
    name="rpmfusion-free"
    display_name="RPM Fusion for Fedora $releasever - Free" 
    metalink="lsjfdasl"
    baseurl="http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/"
    gpgcheck=true
    gpgkey="file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever"


    [[repo.custom_repos]]
    # name="test"
    name=""
    display_name="RPM Fusion for Fedora $releasever - Free" 
    metalink="https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch"
    baseurl="http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/"
    gpgcheck=true
    gpgkey="file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever"

# define multiple types of packages to be included
[package]
# something="fsdkl"
    [package.rpm]
    install=[
        "moreutils",
        "dklassa",
        "jq",
        "ripgrep",
        "gnome-terminal"
    ]
    # install=2

    remove=[
        "gnome-calculator"
    ]


    [package.rpm_group]
    install=[
        "multimedia",
        # "fkasjklfjasdklfjasdklfjaklsdjfadkljsd",
        "sound-and-video"
    ]

    remove=[
        "virtualization"
    ]

[misc]
language="en_US.utf8" # locale -a
# sdlfkas="lasd"
# daksf="lasd"
# keyboard="us" # localectl list-x11-keymap-layouts
# keyboard="fdsasdfasdlkfasdlsdajls" # localectl list-x11-keymap-layouts
timezone="US/Pacific" # cd /usr/share/zoneinfo/posix && find * -type f -or -type l